import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

const STATES = [
  { id: "AL", name: "Alabama", slug: "alabama", seoBlurb: null },
  { id: "AK", name: "Alaska", slug: "alaska", seoBlurb: null },
  { id: "AZ", name: "Arizona", slug: "arizona", seoBlurb: "Arizona card shows bring together collectors from Phoenix, Tucson, and beyond. Find upcoming sports card, Pokémon, and TCG events across the Grand Canyon State." },
  { id: "AR", name: "Arkansas", slug: "arkansas", seoBlurb: null },
  { id: "CA", name: "California", slug: "california", seoBlurb: "California hosts some of the most active card show circuits in the nation. From Los Angeles to the Bay Area, find upcoming sports card shows, Pokémon events, and TCG tournaments near you." },
  { id: "CO", name: "Colorado", slug: "colorado", seoBlurb: null },
  { id: "CT", name: "Connecticut", slug: "connecticut", seoBlurb: null },
  { id: "DE", name: "Delaware", slug: "delaware", seoBlurb: null },
  { id: "FL", name: "Florida", slug: "florida", seoBlurb: "Florida is home to a thriving card show scene with events in Miami, Orlando, Tampa, and Jacksonville. Discover upcoming sports card shows and collectible events across the Sunshine State." },
  { id: "GA", name: "Georgia", slug: "georgia", seoBlurb: "Georgia card shows draw collectors from Atlanta and across the Southeast. Browse upcoming sports card, Pokémon, and TCG events throughout the Peach State." },
  { id: "HI", name: "Hawaii", slug: "hawaii", seoBlurb: null },
  { id: "ID", name: "Idaho", slug: "idaho", seoBlurb: null },
  { id: "IL", name: "Illinois", slug: "illinois", seoBlurb: "Illinois has one of the most active card show circuits in the Midwest. Chicago and surrounding suburbs host regular sports card shows, TCG events, and collectible fairs throughout the year." },
  { id: "IN", name: "Indiana", slug: "indiana", seoBlurb: null },
  { id: "IA", name: "Iowa", slug: "iowa", seoBlurb: null },
  { id: "KS", name: "Kansas", slug: "kansas", seoBlurb: "Kansas card shows bring together collectors from Wichita, Kansas City, and across the Sunflower State. Find upcoming sports card shows, Pokémon events, and TCG tournaments near you." },
  { id: "KY", name: "Kentucky", slug: "kentucky", seoBlurb: null },
  { id: "LA", name: "Louisiana", slug: "louisiana", seoBlurb: null },
  { id: "ME", name: "Maine", slug: "maine", seoBlurb: null },
  { id: "MD", name: "Maryland", slug: "maryland", seoBlurb: null },
  { id: "MA", name: "Massachusetts", slug: "massachusetts", seoBlurb: null },
  { id: "MI", name: "Michigan", slug: "michigan", seoBlurb: null },
  { id: "MN", name: "Minnesota", slug: "minnesota", seoBlurb: null },
  { id: "MS", name: "Mississippi", slug: "mississippi", seoBlurb: null },
  { id: "MO", name: "Missouri", slug: "missouri", seoBlurb: "Missouri card shows are a staple of the Midwest collector community. Find upcoming shows in Kansas City, St. Louis, and across the Show-Me State." },
  { id: "MT", name: "Montana", slug: "montana", seoBlurb: null },
  { id: "NE", name: "Nebraska", slug: "nebraska", seoBlurb: null },
  { id: "NV", name: "Nevada", slug: "nevada", seoBlurb: null },
  { id: "NH", name: "New Hampshire", slug: "new-hampshire", seoBlurb: null },
  { id: "NJ", name: "New Jersey", slug: "new-jersey", seoBlurb: null },
  { id: "NM", name: "New Mexico", slug: "new-mexico", seoBlurb: null },
  { id: "NY", name: "New York", slug: "new-york", seoBlurb: null },
  { id: "NC", name: "North Carolina", slug: "north-carolina", seoBlurb: "North Carolina's card show scene is growing fast. Find upcoming sports card shows, Pokémon events, and collectible fairs in Charlotte, Raleigh, Greensboro, and beyond." },
  { id: "ND", name: "North Dakota", slug: "north-dakota", seoBlurb: null },
  { id: "OH", name: "Ohio", slug: "ohio", seoBlurb: "Ohio is one of the most card-show-active states in the country. Columbus, Cleveland, and Cincinnati all host regular shows. Find upcoming sports card, Pokémon, and TCG events across the Buckeye State." },
  { id: "OK", name: "Oklahoma", slug: "oklahoma", seoBlurb: "Oklahoma card shows bring together collectors from Oklahoma City, Tulsa, and across the Sooner State. Discover upcoming sports card and TCG events near you." },
  { id: "OR", name: "Oregon", slug: "oregon", seoBlurb: null },
  { id: "PA", name: "Pennsylvania", slug: "pennsylvania", seoBlurb: "Pennsylvania has an active card show scene with events in Philadelphia, Pittsburgh, and throughout the state. Find upcoming sports card shows and collectible events near you." },
  { id: "RI", name: "Rhode Island", slug: "rhode-island", seoBlurb: null },
  { id: "SC", name: "South Carolina", slug: "south-carolina", seoBlurb: null },
  { id: "SD", name: "South Dakota", slug: "south-dakota", seoBlurb: null },
  { id: "TN", name: "Tennessee", slug: "tennessee", seoBlurb: "Tennessee hosts a strong card show circuit across Nashville, Memphis, Knoxville, and Chattanooga. Find upcoming sports card shows and TCG events throughout the Volunteer State." },
  { id: "TX", name: "Texas", slug: "texas", seoBlurb: "Texas hosts some of the biggest card shows in the nation. From Dallas-Fort Worth to Houston, San Antonio, and Austin, find upcoming sports card shows, Pokémon events, and TCG tournaments near you." },
  { id: "UT", name: "Utah", slug: "utah", seoBlurb: null },
  { id: "VT", name: "Vermont", slug: "vermont", seoBlurb: null },
  { id: "VA", name: "Virginia", slug: "virginia", seoBlurb: null },
  { id: "WA", name: "Washington", slug: "washington", seoBlurb: null },
  { id: "WV", name: "West Virginia", slug: "west-virginia", seoBlurb: null },
  { id: "WI", name: "Wisconsin", slug: "wisconsin", seoBlurb: null },
  { id: "WY", name: "Wyoming", slug: "wyoming", seoBlurb: null },
];

// Sample shows for dev/demo
const SAMPLE_SHOWS = [
  {
    title: "Dallas Fort Worth Card Show",
    slug: "dallas-fort-worth-card-show-april-2026",
    city: "Arlington",
    state: "TX",
    startDate: new Date("2026-04-05T09:00:00"),
    endDate: new Date("2026-04-06T16:00:00"),
    startTimeLabel: "9:00 AM",
    endTimeLabel: "4:00 PM",
    status: "APPROVED" as const,
    sourceType: "MANUAL" as const,
    isFree: false,
    admissionPrice: "$5",
    tableCount: 300,
    categories: ["Sports Cards", "Pokémon", "TCG"],
    description: "One of the largest card shows in North Texas. Hundreds of dealers, thousands of cards. Free parking.",
    lastVerifiedAt: new Date(),
  },
  {
    title: "Houston Sports Card & Collectibles Show",
    slug: "houston-sports-card-collectibles-show-april-2026",
    city: "Houston",
    state: "TX",
    startDate: new Date("2026-04-12T10:00:00"),
    endDate: new Date("2026-04-12T17:00:00"),
    startTimeLabel: "10:00 AM",
    endTimeLabel: "5:00 PM",
    status: "APPROVED" as const,
    sourceType: "MANUAL" as const,
    isFree: false,
    admissionPrice: "$3",
    tableCount: 150,
    categories: ["Sports Cards", "Memorabilia"],
    description: "Monthly card show at the NRG area featuring sports cards, memorabilia, and autograph guests.",
    lastVerifiedAt: new Date(),
  },
  {
    title: "Ohio Card Show",
    slug: "ohio-card-show-columbus-april-2026",
    city: "Columbus",
    state: "OH",
    startDate: new Date("2026-04-18T09:00:00"),
    endDate: new Date("2026-04-19T15:00:00"),
    startTimeLabel: "9:00 AM",
    endTimeLabel: "3:00 PM",
    status: "APPROVED" as const,
    sourceType: "MANUAL" as const,
    isFree: false,
    admissionPrice: "$5",
    tableCount: 200,
    categories: ["Sports Cards", "TCG"],
    description: "Central Ohio's premier card show. Dealers from across the Midwest.",
    lastVerifiedAt: new Date(),
  },
  {
    title: "Chicago Card Show",
    slug: "chicago-card-show-april-2026",
    city: "Chicago",
    state: "IL",
    startDate: new Date("2026-04-25T10:00:00"),
    endDate: new Date("2026-04-26T16:00:00"),
    startTimeLabel: "10:00 AM",
    endTimeLabel: "4:00 PM",
    status: "APPROVED" as const,
    sourceType: "MANUAL" as const,
    isFree: false,
    admissionPrice: "$6",
    tableCount: 250,
    categories: ["Sports Cards", "Pokémon", "Memorabilia"],
    description: "Chicago's biggest card show returns. Hundreds of dealers from the Midwest and beyond.",
    lastVerifiedAt: new Date(),
  },
  {
    title: "Kansas City Card Show",
    slug: "kansas-city-card-show-april-2026",
    city: "Kansas City",
    state: "MO",
    startDate: new Date("2026-04-11T09:00:00"),
    endDate: new Date("2026-04-11T15:00:00"),
    startTimeLabel: "9:00 AM",
    endTimeLabel: "3:00 PM",
    status: "APPROVED" as const,
    sourceType: "MANUAL" as const,
    isFree: true,
    tableCount: 80,
    categories: ["Sports Cards", "Mixed"],
    description: "Free admission card show in the Kansas City metro. Great for buying, selling, and trading.",
    lastVerifiedAt: new Date(),
  },
  {
    title: "Wichita Sports Card Show",
    slug: "wichita-sports-card-show-april-2026",
    city: "Wichita",
    state: "KS",
    startDate: new Date("2026-04-19T10:00:00"),
    endDate: new Date("2026-04-19T16:00:00"),
    startTimeLabel: "10:00 AM",
    endTimeLabel: "4:00 PM",
    status: "APPROVED" as const,
    sourceType: "MANUAL" as const,
    isFree: false,
    admissionPrice: "$2",
    tableCount: 60,
    categories: ["Sports Cards", "TCG"],
    description: "South Central Kansas's most popular card show. Come buy, sell, and trade with Wichita collectors.",
    lastVerifiedAt: new Date(),
  },
  {
    title: "Atlanta Card Expo",
    slug: "atlanta-card-expo-may-2026",
    city: "Atlanta",
    state: "GA",
    startDate: new Date("2026-05-02T10:00:00"),
    endDate: new Date("2026-05-03T17:00:00"),
    startTimeLabel: "10:00 AM",
    endTimeLabel: "5:00 PM",
    status: "APPROVED" as const,
    sourceType: "MANUAL" as const,
    isFree: false,
    admissionPrice: "$5",
    tableCount: 180,
    categories: ["Sports Cards", "Pokémon", "Memorabilia"],
    description: "The Southeast's premier card show event. Atlanta collectors and dealers welcome.",
    lastVerifiedAt: new Date(),
  },
  {
    title: "Nashville Sports Card Show",
    slug: "nashville-sports-card-show-may-2026",
    city: "Nashville",
    state: "TN",
    startDate: new Date("2026-05-09T09:00:00"),
    endDate: new Date("2026-05-10T15:00:00"),
    startTimeLabel: "9:00 AM",
    endTimeLabel: "3:00 PM",
    status: "APPROVED" as const,
    sourceType: "MANUAL" as const,
    isFree: false,
    admissionPrice: "$4",
    tableCount: 120,
    categories: ["Sports Cards", "TCG"],
    description: "Middle Tennessee's biggest card show. Vendors from across the Southeast.",
    lastVerifiedAt: new Date(),
  },
  {
    title: "Philadelphia Card Show",
    slug: "philadelphia-card-show-may-2026",
    city: "Philadelphia",
    state: "PA",
    startDate: new Date("2026-05-16T10:00:00"),
    endDate: new Date("2026-05-17T16:00:00"),
    startTimeLabel: "10:00 AM",
    endTimeLabel: "4:00 PM",
    status: "APPROVED" as const,
    sourceType: "MANUAL" as const,
    isFree: false,
    admissionPrice: "$5",
    tableCount: 220,
    categories: ["Sports Cards", "Memorabilia", "Autograph Guests"],
    description: "Greater Philadelphia's largest card show with special autograph guests.",
    lastVerifiedAt: new Date(),
  },
  {
    title: "Oklahoma City Card Show",
    slug: "oklahoma-city-card-show-may-2026",
    city: "Oklahoma City",
    state: "OK",
    startDate: new Date("2026-05-23T10:00:00"),
    endDate: new Date("2026-05-23T16:00:00"),
    startTimeLabel: "10:00 AM",
    endTimeLabel: "4:00 PM",
    status: "APPROVED" as const,
    sourceType: "MANUAL" as const,
    isFree: true,
    tableCount: 70,
    categories: ["Sports Cards", "Mixed"],
    description: "Free admission show in OKC. Great selection of sports cards, vintage, and modern wax.",
    lastVerifiedAt: new Date(),
  },
  {
    title: "Los Angeles Card & Collectibles Show",
    slug: "los-angeles-card-collectibles-show-may-2026",
    city: "Los Angeles",
    state: "CA",
    startDate: new Date("2026-05-30T10:00:00"),
    endDate: new Date("2026-05-31T17:00:00"),
    startTimeLabel: "10:00 AM",
    endTimeLabel: "5:00 PM",
    status: "APPROVED" as const,
    sourceType: "MANUAL" as const,
    isFree: false,
    admissionPrice: "$8",
    tableCount: 400,
    categories: ["Sports Cards", "Pokémon", "Memorabilia", "Autograph Guests"],
    description: "Southern California's biggest annual card show event.",
    lastVerifiedAt: new Date(),
  },
  {
    title: "Charlotte Card Show",
    slug: "charlotte-card-show-may-2026",
    city: "Charlotte",
    state: "NC",
    startDate: new Date("2026-05-02T09:00:00"),
    endDate: new Date("2026-05-02T15:00:00"),
    startTimeLabel: "9:00 AM",
    endTimeLabel: "3:00 PM",
    status: "APPROVED" as const,
    sourceType: "MANUAL" as const,
    isFree: false,
    admissionPrice: "$3",
    tableCount: 90,
    categories: ["Sports Cards", "TCG"],
    description: "Monthly card show in the Queen City. All major sports and TCG represented.",
    lastVerifiedAt: new Date(),
  },
];

async function main() {
  console.log("🌱 Seeding database...");

  // Upsert all 50 states
  console.log("  → Seeding states...");
  for (const state of STATES) {
    await db.state.upsert({
      where: { id: state.id },
      update: { name: state.name, slug: state.slug, seoBlurb: state.seoBlurb },
      create: state,
    });
  }
  console.log(`  ✓ ${STATES.length} states seeded`);

  // Seed sample shows
  console.log("  → Seeding sample shows...");
  let created = 0;
  for (const show of SAMPLE_SHOWS) {
    await db.show.upsert({
      where: { slug: show.slug },
      update: {},
      create: show,
    });
    created++;
  }
  console.log(`  ✓ ${created} sample shows seeded`);

  console.log("✅ Seed complete");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
