import { PrismaClient } from "../generated/prisma-client";

const db = new PrismaClient();

const STATES = [
  { id: "AL", name: "Alabama", slug: "alabama", seoBlurb: null },
  { id: "AK", name: "Alaska", slug: "alaska", seoBlurb: null },
  { id: "AZ", name: "Arizona", slug: "arizona", seoBlurb: null },
  { id: "AR", name: "Arkansas", slug: "arkansas", seoBlurb: null },
  { id: "CA", name: "California", slug: "california", seoBlurb: null },
  { id: "CO", name: "Colorado", slug: "colorado", seoBlurb: "Colorado collectors regularly travel between Denver, Colorado Springs, and the Front Range for sports card and TCG weekends. Browse upcoming shows with event details in one place." },
  { id: "CT", name: "Connecticut", slug: "connecticut", seoBlurb: null },
  { id: "DE", name: "Delaware", slug: "delaware", seoBlurb: null },
  { id: "FL", name: "Florida", slug: "florida", seoBlurb: null },
  { id: "GA", name: "Georgia", slug: "georgia", seoBlurb: null },
  { id: "HI", name: "Hawaii", slug: "hawaii", seoBlurb: null },
  { id: "ID", name: "Idaho", slug: "idaho", seoBlurb: null },
  { id: "IL", name: "Illinois", slug: "illinois", seoBlurb: "Illinois card shows draw collectors from Chicago, the suburbs, and across the Midwest. Find upcoming sports card, Pokemon, and TCG events with dates, venues, and admission details." },
  { id: "IN", name: "Indiana", slug: "indiana", seoBlurb: null },
  { id: "IA", name: "Iowa", slug: "iowa", seoBlurb: "Iowa card shows give collectors a dependable way to plan quick weekend trips across Des Moines, Cedar Rapids, and the rest of the state. Browse upcoming sports card and TCG events here." },
  { id: "KS", name: "Kansas", slug: "kansas", seoBlurb: "Kansas card shows are a core part of the launch footprint for Card Show Nation. Browse upcoming shows in Wichita, Overland Park, and across the state with venue, admission, and vendor details." },
  { id: "KY", name: "Kentucky", slug: "kentucky", seoBlurb: null },
  { id: "LA", name: "Louisiana", slug: "louisiana", seoBlurb: null },
  { id: "ME", name: "Maine", slug: "maine", seoBlurb: null },
  { id: "MD", name: "Maryland", slug: "maryland", seoBlurb: null },
  { id: "MA", name: "Massachusetts", slug: "massachusetts", seoBlurb: null },
  { id: "MI", name: "Michigan", slug: "michigan", seoBlurb: null },
  { id: "MN", name: "Minnesota", slug: "minnesota", seoBlurb: null },
  { id: "MS", name: "Mississippi", slug: "mississippi", seoBlurb: null },
  { id: "MO", name: "Missouri", slug: "missouri", seoBlurb: "Missouri is one of the strongest early markets for Card Show Nation, with collectors moving between Kansas City, St. Louis, and regional weekend shows. Explore current listings and promoter details." },
  { id: "MT", name: "Montana", slug: "montana", seoBlurb: null },
  { id: "NE", name: "Nebraska", slug: "nebraska", seoBlurb: "Nebraska card shows offer a practical regional trip for collectors across Omaha, Lincoln, and neighboring states. Browse upcoming events with venue, admission, and table info." },
  { id: "NV", name: "Nevada", slug: "nevada", seoBlurb: null },
  { id: "NH", name: "New Hampshire", slug: "new-hampshire", seoBlurb: null },
  { id: "NJ", name: "New Jersey", slug: "new-jersey", seoBlurb: null },
  { id: "NM", name: "New Mexico", slug: "new-mexico", seoBlurb: null },
  { id: "NY", name: "New York", slug: "new-york", seoBlurb: null },
  { id: "NC", name: "North Carolina", slug: "north-carolina", seoBlurb: null },
  { id: "ND", name: "North Dakota", slug: "north-dakota", seoBlurb: null },
  { id: "OH", name: "Ohio", slug: "ohio", seoBlurb: null },
  { id: "OK", name: "Oklahoma", slug: "oklahoma", seoBlurb: "Oklahoma collectors can use Card Show Nation to quickly find shows in Oklahoma City, Tulsa, and nearby regional markets. Browse dates, venues, and vendor details for upcoming weekends." },
  { id: "OR", name: "Oregon", slug: "oregon", seoBlurb: null },
  { id: "PA", name: "Pennsylvania", slug: "pennsylvania", seoBlurb: null },
  { id: "RI", name: "Rhode Island", slug: "rhode-island", seoBlurb: null },
  { id: "SC", name: "South Carolina", slug: "south-carolina", seoBlurb: null },
  { id: "SD", name: "South Dakota", slug: "south-dakota", seoBlurb: null },
  { id: "TN", name: "Tennessee", slug: "tennessee", seoBlurb: null },
  { id: "TX", name: "Texas", slug: "texas", seoBlurb: "Texas remains a strong expansion market for Card Show Nation. Browse upcoming sports card and TCG events by city, venue, and date as the directory grows." },
  { id: "UT", name: "Utah", slug: "utah", seoBlurb: null },
  { id: "VT", name: "Vermont", slug: "vermont", seoBlurb: null },
  { id: "VA", name: "Virginia", slug: "virginia", seoBlurb: null },
  { id: "WA", name: "Washington", slug: "washington", seoBlurb: null },
  { id: "WV", name: "West Virginia", slug: "west-virginia", seoBlurb: null },
  { id: "WI", name: "Wisconsin", slug: "wisconsin", seoBlurb: null },
  { id: "WY", name: "Wyoming", slug: "wyoming", seoBlurb: null },
];

const ORGANIZERS = [
  {
    id: "org-kansas-card-show",
    name: "Kansas Card Show",
    websiteUrl: "https://kansascardshow.com",
    facebookUrl: null,
    instagramUrl: null,
    verified: true,
  },
  {
    id: "org-midwest-hobby-events",
    name: "Midwest Hobby Events",
    websiteUrl: null,
    facebookUrl: null,
    instagramUrl: null,
    verified: true,
  },
  {
    id: "org-red-dirt-collectibles",
    name: "Red Dirt Collectibles",
    websiteUrl: null,
    facebookUrl: null,
    instagramUrl: null,
    verified: true,
  },
  {
    id: "org-gateway-card-promotions",
    name: "Gateway Card Promotions",
    websiteUrl: null,
    facebookUrl: null,
    instagramUrl: null,
    verified: true,
  },
  {
    id: "org-plains-card-market",
    name: "Plains Card Market",
    websiteUrl: null,
    facebookUrl: null,
    instagramUrl: null,
    verified: true,
  },
];

const VENUES = [
  {
    id: "venue-wichita-expo",
    name: "Wichita Sports Forum",
    address1: "2668 N Greenwich Rd",
    address2: null,
    city: "Wichita",
    state: "KS",
    postalCode: "67226",
    latitude: 37.7453,
    longitude: -97.2502,
    parkingInfo: "Free parking surrounds the venue.",
    loadInInfo: "Dealer setup opens at 7:30 AM.",
  },
  {
    id: "venue-overland-park",
    name: "Overland Park Event Center",
    address1: "6000 College Blvd",
    address2: null,
    city: "Overland Park",
    state: "KS",
    postalCode: "66211",
    latitude: 38.9152,
    longitude: -94.6720,
    parkingInfo: "Surface parking is free on weekends.",
    loadInInfo: "Vendor check-in starts at 6:45 AM.",
  },
  {
    id: "venue-kansas-city",
    name: "KCI Expo Hall",
    address1: "11730 N Ambassador Dr",
    address2: null,
    city: "Kansas City",
    state: "MO",
    postalCode: "64153",
    latitude: 39.2907,
    longitude: -94.7229,
    parkingInfo: "Main lot parking is included with admission.",
    loadInInfo: "Dealer load-in starts at 7:00 AM on Saturday.",
  },
  {
    id: "venue-st-louis",
    name: "St. Charles Convention Center",
    address1: "1 Convention Center Plz",
    address2: null,
    city: "St. Charles",
    state: "MO",
    postalCode: "63303",
    latitude: 38.7882,
    longitude: -90.4966,
    parkingInfo: "Free attached lot parking.",
    loadInInfo: "Promoter staff begins vendor check-in at 7:00 AM.",
  },
  {
    id: "venue-okc",
    name: "OKC Event Hall",
    address1: "311 S Klein Ave",
    address2: null,
    city: "Oklahoma City",
    state: "OK",
    postalCode: "73108",
    latitude: 35.4630,
    longitude: -97.5170,
    parkingInfo: "Paid parking garage next to the hall.",
    loadInInfo: "Vendor entry opens at 8:00 AM.",
  },
  {
    id: "venue-tulsa",
    name: "Tulsa Expo Market Hall",
    address1: "4145 E 21st St",
    address2: null,
    city: "Tulsa",
    state: "OK",
    postalCode: "74114",
    latitude: 36.1380,
    longitude: -95.9510,
    parkingInfo: "Free parking available around Expo Square.",
    loadInInfo: "Trade night setup begins Friday at 5:00 PM.",
  },
  {
    id: "venue-omaha",
    name: "Omaha Fire Hall Event Center",
    address1: "6005 Grover St",
    address2: null,
    city: "Omaha",
    state: "NE",
    postalCode: "68106",
    latitude: 41.2390,
    longitude: -96.0010,
    parkingInfo: "Free surface parking behind the hall.",
    loadInInfo: "Dealer setup starts at 7:00 AM.",
  },
  {
    id: "venue-lincoln",
    name: "Lincoln Event Pavilion",
    address1: "4100 Pioneer Woods Dr",
    address2: null,
    city: "Lincoln",
    state: "NE",
    postalCode: "68506",
    latitude: 40.7860,
    longitude: -96.6393,
    parkingInfo: "Free parking lot on site.",
    loadInInfo: "Vendor doors open at 7:30 AM.",
  },
  {
    id: "venue-des-moines",
    name: "Iowa Events Hall",
    address1: "730 3rd St",
    address2: null,
    city: "Des Moines",
    state: "IA",
    postalCode: "50309",
    latitude: 41.5866,
    longitude: -93.6255,
    parkingInfo: "Garage parking is available across the street.",
    loadInInfo: "Dealers may set up starting at 6:30 AM.",
  },
  {
    id: "venue-chicago",
    name: "Chicagoland Convention Hall",
    address1: "5555 N River Rd",
    address2: null,
    city: "Rosemont",
    state: "IL",
    postalCode: "60018",
    latitude: 41.9813,
    longitude: -87.8748,
    parkingInfo: "Convention parking garage available onsite.",
    loadInInfo: "Vendor move-in opens at 7:00 AM.",
  },
];

const SAMPLE_SHOWS = [
  {
    title: "Kansas Card Show Spring Weekend",
    slug: "kansas-card-show-spring-weekend-wichita-2026",
    description:
      "A collector-first weekend with sports cards, Pokemon, and TCG tables across vintage, modern, wax, and singles. This sample listing shows the level of detail Card Show Nation can support for a flagship regional event.",
    status: "APPROVED" as const,
    sourceType: "MANUAL" as const,
    timezone: "America/Chicago",
    startDate: new Date("2026-04-25T09:00:00"),
    endDate: new Date("2026-04-25T16:00:00"),
    startTimeLabel: "9:00 AM",
    endTimeLabel: "4:00 PM",
    city: "Wichita",
    state: "KS",
    isFree: false,
    admissionPrice: "$5",
    admissionNotes: "Kids 12 and under are free with a paid adult.",
    tableCount: 140,
    vendorDetails: "Dealer floor is nearly sold out. Promoter waitlist is open.",
    websiteUrl: "https://kansascardshow.com",
    facebookUrl: null,
    ticketUrl: null,
    parkingInfo: "Free parking surrounds the venue.",
    loadInInfo: "Dealer setup opens at 7:30 AM.",
    venueNotes: "Main hall entrance opens to the public at 8:45 AM.",
    categories: ["Sports Cards", "Pokemon", "TCG"],
    lastVerifiedAt: new Date("2026-04-10T12:00:00"),
    expiresAt: new Date("2026-04-26T23:59:59"),
    featuredRank: 1,
    organizerId: "org-kansas-card-show",
    venueId: "venue-wichita-expo",
  },
  {
    title: "Overland Park Card and TCG Weekend",
    slug: "overland-park-card-and-tcg-weekend-2026",
    description:
      "A strong suburban Kansas City market event with modern sports cards, graded inventory, sealed Pokemon product, and family-friendly traffic.",
    status: "APPROVED" as const,
    sourceType: "MANUAL" as const,
    timezone: "America/Chicago",
    startDate: new Date("2026-05-09T09:00:00"),
    endDate: new Date("2026-05-09T15:00:00"),
    startTimeLabel: "9:00 AM",
    endTimeLabel: "3:00 PM",
    city: "Overland Park",
    state: "KS",
    isFree: false,
    admissionPrice: "$3",
    admissionNotes: "Early buyer entry starts at 8:00 AM for $10.",
    tableCount: 85,
    vendorDetails: "A few dealer tables remain. TCG-focused vendors encouraged.",
    websiteUrl: null,
    facebookUrl: null,
    ticketUrl: null,
    parkingInfo: "Surface parking is free on weekends.",
    loadInInfo: "Vendor check-in starts at 6:45 AM.",
    venueNotes: null,
    categories: ["Sports Cards", "Pokemon", "TCG"],
    lastVerifiedAt: new Date("2026-04-11T12:00:00"),
    expiresAt: new Date("2026-05-10T23:59:59"),
    featuredRank: 3,
    organizerId: "org-kansas-card-show",
    venueId: "venue-overland-park",
  },
  {
    title: "Kansas City Card Weekend",
    slug: "kansas-city-card-weekend-2026",
    description:
      "A metro draw for Missouri and Kansas collectors featuring vintage showcases, bargain boxes, and a broad dealer floor.",
    status: "APPROVED" as const,
    sourceType: "MANUAL" as const,
    timezone: "America/Chicago",
    startDate: new Date("2026-05-02T09:00:00"),
    endDate: new Date("2026-05-03T15:00:00"),
    startTimeLabel: "9:00 AM",
    endTimeLabel: "3:00 PM",
    city: "Kansas City",
    state: "MO",
    isFree: false,
    admissionPrice: "$7 weekend pass",
    admissionNotes: "Saturday-only admission is $5.",
    tableCount: 160,
    vendorDetails: "Full dealer floor plus Sunday trade tables.",
    websiteUrl: null,
    facebookUrl: null,
    ticketUrl: null,
    parkingInfo: "Main lot parking is included with admission.",
    loadInInfo: "Dealer load-in starts at 7:00 AM on Saturday.",
    venueNotes: "Trade night runs after close on Saturday.",
    categories: ["Sports Cards", "Pokemon", "Memorabilia"],
    lastVerifiedAt: new Date("2026-04-12T12:00:00"),
    expiresAt: new Date("2026-05-04T23:59:59"),
    featuredRank: 2,
    organizerId: "org-midwest-hobby-events",
    venueId: "venue-kansas-city",
  },
  {
    title: "St. Louis Sports Card Showcase",
    slug: "st-louis-sports-card-showcase-2026",
    description:
      "A larger regional show built around sports cards with autograph guests, vintage showcases, and a broad Midwest dealer mix.",
    status: "APPROVED" as const,
    sourceType: "MANUAL" as const,
    timezone: "America/Chicago",
    startDate: new Date("2026-05-16T10:00:00"),
    endDate: new Date("2026-05-17T16:00:00"),
    startTimeLabel: "10:00 AM",
    endTimeLabel: "4:00 PM",
    city: "St. Charles",
    state: "MO",
    isFree: false,
    admissionPrice: "$8",
    admissionNotes: "VIP early entry starts at 9:00 AM.",
    tableCount: 220,
    vendorDetails: "Promoter is accepting a limited number of premium corner booths.",
    websiteUrl: null,
    facebookUrl: null,
    ticketUrl: null,
    parkingInfo: "Free attached lot parking.",
    loadInInfo: "Promoter staff begins vendor check-in at 7:00 AM.",
    venueNotes: null,
    categories: ["Sports Cards", "Memorabilia", "Autograph Guests"],
    lastVerifiedAt: new Date("2026-04-13T12:00:00"),
    expiresAt: new Date("2026-05-18T23:59:59"),
    featuredRank: 4,
    organizerId: "org-gateway-card-promotions",
    venueId: "venue-st-louis",
  },
  {
    title: "Oklahoma City Collectors Expo",
    slug: "oklahoma-city-collectors-expo-2026",
    description:
      "A broad hobby event with sports cards, Pokemon, and sealed product sellers serving the OKC market and surrounding states.",
    status: "APPROVED" as const,
    sourceType: "MANUAL" as const,
    timezone: "America/Chicago",
    startDate: new Date("2026-05-23T10:00:00"),
    endDate: new Date("2026-05-23T16:00:00"),
    startTimeLabel: "10:00 AM",
    endTimeLabel: "4:00 PM",
    city: "Oklahoma City",
    state: "OK",
    isFree: true,
    admissionPrice: null,
    admissionNotes: "Free public admission all day.",
    tableCount: 90,
    vendorDetails: "Dealer registration remains open through May 10.",
    websiteUrl: null,
    facebookUrl: null,
    ticketUrl: null,
    parkingInfo: "Paid parking garage next to the hall.",
    loadInInfo: "Vendor entry opens at 8:00 AM.",
    venueNotes: null,
    categories: ["Sports Cards", "Pokemon", "TCG"],
    lastVerifiedAt: new Date("2026-04-14T12:00:00"),
    expiresAt: new Date("2026-05-24T23:59:59"),
    featuredRank: null,
    organizerId: "org-red-dirt-collectibles",
    venueId: "venue-okc",
  },
  {
    title: "Tulsa Trade Night and Card Show",
    slug: "tulsa-trade-night-and-card-show-2026",
    description:
      "A one-two punch weekend with a Friday trade night and a Saturday card show focused on active buying, selling, and trading.",
    status: "APPROVED" as const,
    sourceType: "MANUAL" as const,
    timezone: "America/Chicago",
    startDate: new Date("2026-06-06T09:00:00"),
    endDate: new Date("2026-06-06T15:00:00"),
    startTimeLabel: "9:00 AM",
    endTimeLabel: "3:00 PM",
    city: "Tulsa",
    state: "OK",
    isFree: false,
    admissionPrice: "$5",
    admissionNotes: "Friday trade night is free with Saturday admission.",
    tableCount: 75,
    vendorDetails: "Promoter expects a fast-moving singles-heavy floor.",
    websiteUrl: null,
    facebookUrl: null,
    ticketUrl: null,
    parkingInfo: "Free parking available around Expo Square.",
    loadInInfo: "Trade night setup begins Friday at 5:00 PM.",
    venueNotes: "Saturday opens with a trade pit near the entrance.",
    categories: ["Sports Cards", "Trade Night", "TCG"],
    lastVerifiedAt: new Date("2026-04-14T12:00:00"),
    expiresAt: new Date("2026-06-07T23:59:59"),
    featuredRank: null,
    organizerId: "org-red-dirt-collectibles",
    venueId: "venue-tulsa",
  },
  {
    title: "Omaha Hobby Card Show",
    slug: "omaha-hobby-card-show-2026",
    description:
      "A Nebraska regional event with strong sports card inventory, wax, and value tables aimed at local collectors and weekend travelers.",
    status: "APPROVED" as const,
    sourceType: "MANUAL" as const,
    timezone: "America/Chicago",
    startDate: new Date("2026-05-30T09:00:00"),
    endDate: new Date("2026-05-30T15:00:00"),
    startTimeLabel: "9:00 AM",
    endTimeLabel: "3:00 PM",
    city: "Omaha",
    state: "NE",
    isFree: false,
    admissionPrice: "$4",
    admissionNotes: "Cash and card accepted at the door.",
    tableCount: 70,
    vendorDetails: "Promoter is still accepting local dealer applications.",
    websiteUrl: null,
    facebookUrl: null,
    ticketUrl: null,
    parkingInfo: "Free surface parking behind the hall.",
    loadInInfo: "Dealer setup starts at 7:00 AM.",
    venueNotes: null,
    categories: ["Sports Cards", "Pokemon", "Mixed"],
    lastVerifiedAt: new Date("2026-04-15T12:00:00"),
    expiresAt: new Date("2026-05-31T23:59:59"),
    featuredRank: null,
    organizerId: "org-plains-card-market",
    venueId: "venue-omaha",
  },
  {
    title: "Lincoln Card and Collectibles Market",
    slug: "lincoln-card-and-collectibles-market-2026",
    description:
      "A collector-focused Nebraska weekend show with sports cards, Pokemon, and entry-level table pricing for smaller dealers.",
    status: "APPROVED" as const,
    sourceType: "MANUAL" as const,
    timezone: "America/Chicago",
    startDate: new Date("2026-06-13T10:00:00"),
    endDate: new Date("2026-06-13T16:00:00"),
    startTimeLabel: "10:00 AM",
    endTimeLabel: "4:00 PM",
    city: "Lincoln",
    state: "NE",
    isFree: true,
    admissionPrice: null,
    admissionNotes: "Free public admission.",
    tableCount: 55,
    vendorDetails: "Low-cost vendor tables available for new dealers.",
    websiteUrl: null,
    facebookUrl: null,
    ticketUrl: null,
    parkingInfo: "Free parking lot on site.",
    loadInInfo: "Vendor doors open at 7:30 AM.",
    venueNotes: null,
    categories: ["Sports Cards", "Pokemon", "TCG"],
    lastVerifiedAt: new Date("2026-04-15T12:00:00"),
    expiresAt: new Date("2026-06-14T23:59:59"),
    featuredRank: null,
    organizerId: "org-plains-card-market",
    venueId: "venue-lincoln",
  },
  {
    title: "Des Moines Sports Card Show",
    slug: "des-moines-sports-card-show-2026",
    description:
      "A growing Iowa sports card event with modern singles, grading-ready inventory, and family-friendly hours.",
    status: "APPROVED" as const,
    sourceType: "MANUAL" as const,
    timezone: "America/Chicago",
    startDate: new Date("2026-06-20T09:00:00"),
    endDate: new Date("2026-06-20T15:00:00"),
    startTimeLabel: "9:00 AM",
    endTimeLabel: "3:00 PM",
    city: "Des Moines",
    state: "IA",
    isFree: false,
    admissionPrice: "$3",
    admissionNotes: "Kids 10 and under are free.",
    tableCount: 65,
    vendorDetails: "Sports cards lead the floor, with a smaller TCG section.",
    websiteUrl: null,
    facebookUrl: null,
    ticketUrl: null,
    parkingInfo: "Garage parking is available across the street.",
    loadInInfo: "Dealers may set up starting at 6:30 AM.",
    venueNotes: null,
    categories: ["Sports Cards", "TCG"],
    lastVerifiedAt: new Date("2026-04-15T12:00:00"),
    expiresAt: new Date("2026-06-21T23:59:59"),
    featuredRank: null,
    organizerId: "org-midwest-hobby-events",
    venueId: "venue-des-moines",
  },
  {
    title: "Chicagoland Card Expo",
    slug: "chicagoland-card-expo-2026",
    description:
      "A larger Illinois market event with modern, vintage, memorabilia, and Pokemon inventory from dealers across the region.",
    status: "APPROVED" as const,
    sourceType: "MANUAL" as const,
    timezone: "America/Chicago",
    startDate: new Date("2026-06-27T10:00:00"),
    endDate: new Date("2026-06-28T16:00:00"),
    startTimeLabel: "10:00 AM",
    endTimeLabel: "4:00 PM",
    city: "Rosemont",
    state: "IL",
    isFree: false,
    admissionPrice: "$10 weekend pass",
    admissionNotes: "Early entry badge available online only.",
    tableCount: 240,
    vendorDetails: "Dealer floor is full with a waitlist for premium placement.",
    websiteUrl: null,
    facebookUrl: null,
    ticketUrl: null,
    parkingInfo: "Convention parking garage available onsite.",
    loadInInfo: "Vendor move-in opens at 7:00 AM.",
    venueNotes: "Main stage programming begins at noon on Saturday.",
    categories: ["Sports Cards", "Pokemon", "Memorabilia"],
    lastVerifiedAt: new Date("2026-04-16T12:00:00"),
    expiresAt: new Date("2026-06-29T23:59:59"),
    featuredRank: null,
    organizerId: "org-midwest-hobby-events",
    venueId: "venue-chicago",
  },
];

const LEGACY_SAMPLE_SLUGS = [
  "dallas-fort-worth-card-show-april-2026",
  "houston-sports-card-collectibles-show-april-2026",
  "ohio-card-show-columbus-april-2026",
  "chicago-card-show-april-2026",
  "kansas-city-card-show-april-2026",
  "wichita-sports-card-show-april-2026",
  "atlanta-card-expo-may-2026",
  "nashville-sports-card-show-may-2026",
  "philadelphia-card-show-may-2026",
  "oklahoma-city-card-show-may-2026",
  "los-angeles-card-collectibles-show-may-2026",
  "charlotte-card-show-may-2026",
];

async function main() {
  console.log("Seeding database...");

  for (const state of STATES) {
    await db.state.upsert({
      where: { id: state.id },
      update: {
        name: state.name,
        slug: state.slug,
        seoBlurb: state.seoBlurb,
      },
      create: state,
    });
  }

  console.log(`Seeded ${STATES.length} states`);

  for (const organizer of ORGANIZERS) {
    await db.organizer.upsert({
      where: { id: organizer.id },
      update: {
        name: organizer.name,
        websiteUrl: organizer.websiteUrl,
        facebookUrl: organizer.facebookUrl,
        instagramUrl: organizer.instagramUrl,
        verified: organizer.verified,
      },
      create: organizer,
    });
  }

  console.log(`Seeded ${ORGANIZERS.length} organizers`);

  for (const venue of VENUES) {
    await db.venue.upsert({
      where: { id: venue.id },
      update: {
        name: venue.name,
        address1: venue.address1,
        address2: venue.address2,
        city: venue.city,
        state: venue.state,
        postalCode: venue.postalCode,
        latitude: venue.latitude,
        longitude: venue.longitude,
        parkingInfo: venue.parkingInfo,
        loadInInfo: venue.loadInInfo,
      },
      create: venue,
    });
  }

  console.log(`Seeded ${VENUES.length} venues`);

  await db.show.deleteMany({
    where: {
      slug: {
        in: LEGACY_SAMPLE_SLUGS,
      },
    },
  });

  for (const show of SAMPLE_SHOWS) {
    await db.show.upsert({
      where: { slug: show.slug },
      update: show,
      create: show,
    });
  }

  console.log(`Seeded ${SAMPLE_SHOWS.length} sample shows`);
  console.log("Seed complete");
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
